const nodemailer = require('nodemailer');

let transporter = null;
let testAccount = null;

/**
 * Initialize Nodemailer with a free Ethereal test account.
 * No sign-up needed — Ethereal generates a disposable inbox on the fly.
 */
async function initMailer() {
  if (transporter) return transporter;

  testAccount = await nodemailer.createTestAccount();
  transporter = nodemailer.createTransport({
    host: 'smtp.ethereal.email',
    port: 587,
    secure: false,
    auth: {
      user: testAccount.user,
      pass: testAccount.pass,
    },
  });

  console.log('📧 Ethereal email ready');
  console.log(`   Inbox: https://ethereal.email/messages`);
  console.log(`   User:  ${testAccount.user}`);
  console.log(`   Pass:  ${testAccount.pass}`);

  return transporter;
}

/**
 * Send an email and return the Ethereal preview URL for viewing it.
 */
async function sendMail({ to, subject, html }) {
  const mail = await initMailer();
  const info = await mail.sendMail({
    from: '"IWMS System" <noreply@iwms.io>',
    to,
    subject,
    html,
  });
  const previewUrl = nodemailer.getTestMessageUrl(info);
  console.log(`📬 Email sent → ${previewUrl}`);
  return { messageId: info.messageId, previewUrl };
}

// ── Email templates ────────────────────────────────────────────

function weeklyReportHtml({ stats, tasks, topEmployees }) {
  const date = new Date().toLocaleDateString('en-US', { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' });
  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><title>Weekly IWMS Report</title></head>
<body style="font-family:Inter,Arial,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:32px">
  <div style="max-width:600px;margin:0 auto">
    <div style="background:linear-gradient(135deg,#6366f1,#8b5cf6);padding:32px;border-radius:16px 16px 0 0;text-align:center">
      <h1 style="margin:0;font-size:28px;font-weight:800;color:#fff">📊 Weekly Report</h1>
      <p style="margin:8px 0 0;color:#c7d2fe;font-size:14px">${date}</p>
    </div>
    <div style="background:#1e293b;padding:32px;border-radius:0 0 16px 16px">

      <h2 style="color:#94a3b8;font-size:13px;text-transform:uppercase;letter-spacing:0.1em;margin:0 0 16px">Attendance Summary</h2>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-bottom:32px">
        ${[
          { label: 'Present', value: stats.present, color: '#10b981' },
          { label: 'Late',    value: stats.late,    color: '#f59e0b' },
          { label: 'Absent',  value: stats.absent,  color: '#ef4444' },
          { label: 'On Leave',value: stats.onLeave, color: '#8b5cf6' },
        ].map(s => `
          <div style="background:#0f172a;padding:16px;border-radius:10px;border-left:3px solid ${s.color}">
            <div style="font-size:28px;font-weight:800;color:${s.color}">${s.value}</div>
            <div style="font-size:12px;color:#64748b;margin-top:4px">${s.label}</div>
          </div>
        `).join('')}
      </div>

      <h2 style="color:#94a3b8;font-size:13px;text-transform:uppercase;letter-spacing:0.1em;margin:0 0 16px">Task Progress</h2>
      <div style="background:#0f172a;border-radius:10px;padding:16px;margin-bottom:32px">
        ${tasks.map(t => `
          <div style="display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px solid #1e293b">
            <span style="font-size:13px;color:#e2e8f0">${t.title}</span>
            <span style="font-size:11px;background:${t.status === 'done' ? '#10b98120' : '#6366f120'};color:${t.status === 'done' ? '#10b981' : '#6366f1'};padding:2px 10px;border-radius:20px">${t.status}</span>
          </div>
        `).join('')}
      </div>

      <p style="color:#475569;font-size:12px;text-align:center;margin:0">
        Generated by IWMS · Integrated Workforce Management System<br>
        <a href="http://localhost:3000" style="color:#6366f1">Open Dashboard →</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

function lateAlertHtml({ lateEmployees, date }) {
  return `
<!DOCTYPE html>
<html>
<body style="font-family:Inter,Arial,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:32px">
  <div style="max-width:520px;margin:0 auto;background:#1e293b;border-radius:16px;overflow:hidden">
    <div style="background:#f59e0b;padding:24px;text-align:center">
      <h1 style="margin:0;color:#0f172a;font-size:20px;font-weight:800">⚠️ Late Attendance Alert</h1>
      <p style="margin:6px 0 0;color:#451a03;font-size:13px">${date}</p>
    </div>
    <div style="padding:24px">
      <p style="color:#94a3b8;font-size:14px;margin:0 0 16px">The following employees have not clocked in as of 10:00 AM:</p>
      ${lateEmployees.map(e => `
        <div style="background:#0f172a;border-radius:8px;padding:12px 16px;margin-bottom:8px;display:flex;align-items:center;gap:12px">
          <div style="width:36px;height:36px;border-radius:50%;background:#f59e0b20;border:2px solid #f59e0b40;display:flex;align-items:center;justify-content:center;font-weight:700;color:#f59e0b;font-size:14px">${e.avatar}</div>
          <div>
            <p style="margin:0;font-size:14px;font-weight:600;color:#e2e8f0">${e.name}</p>
            <p style="margin:2px 0 0;font-size:12px;color:#64748b">${e.department} · ${e.position}</p>
          </div>
          <span style="margin-left:auto;font-size:11px;background:#ef444420;color:#ef4444;padding:2px 10px;border-radius:20px">No record</span>
        </div>
      `).join('')}
      <p style="color:#475569;font-size:12px;margin:16px 0 0;text-align:center">
        <a href="http://localhost:3000/attendance" style="color:#6366f1">View Attendance Console →</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

function overtimeAlertHtml({ employee, hoursWorked, date }) {
  return `
<!DOCTYPE html>
<html>
<body style="font-family:Inter,Arial,sans-serif;background:#0f172a;color:#e2e8f0;margin:0;padding:32px">
  <div style="max-width:480px;margin:0 auto;background:#1e293b;border-radius:16px;overflow:hidden">
    <div style="background:linear-gradient(135deg,#ef4444,#dc2626);padding:24px;text-align:center">
      <h1 style="margin:0;color:#fff;font-size:20px;font-weight:800">🔴 Overtime Alert</h1>
    </div>
    <div style="padding:24px">
      <p style="color:#94a3b8;font-size:14px;margin:0 0 16px">An employee has exceeded 9 hours of work today:</p>
      <div style="background:#0f172a;border-radius:10px;padding:20px;text-align:center">
        <div style="width:56px;height:56px;border-radius:50%;background:#ef444420;border:2px solid #ef444450;margin:0 auto 12px;display:flex;align-items:center;justify-content:center;font-size:20px;font-weight:800;color:#ef4444">${employee.avatar}</div>
        <p style="font-size:18px;font-weight:700;color:#e2e8f0;margin:0">${employee.name}</p>
        <p style="font-size:13px;color:#64748b;margin:4px 0 16px">${employee.department} · ${employee.position}</p>
        <div style="background:#ef444415;border-radius:8px;padding:12px">
          <span style="font-size:32px;font-weight:800;color:#ef4444">${hoursWorked.toFixed(1)}h</span>
          <p style="margin:4px 0 0;font-size:12px;color:#94a3b8">worked today · ${date}</p>
        </div>
      </div>
      <p style="color:#475569;font-size:12px;margin:16px 0 0;text-align:center">
        <a href="http://localhost:3000/attendance" style="color:#6366f1">View Full Attendance →</a>
      </p>
    </div>
  </div>
</body>
</html>`;
}

module.exports = { sendMail, weeklyReportHtml, lateAlertHtml, overtimeAlertHtml, initMailer };
